{{- if ne .Values.createClusterRole false }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: zesty
  labels:
    app.kubernetes.io/instance: zesty
    app.kubernetes.io/name: zesty
rules:
  - apiGroups:
      - ""
    resources:
      - pods
      - events
      - configmaps
      - persistentvolumeclaims
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - apps
    resources:
      - deployments
      - replicasets
      - daemonsets
      - statefulsets
    verbs:
      - get
      - list
      - watch
{{- end -}}
