apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: "{{ .Release.Name }}"
  labels:
    app.kubernetes.io/instance: zesty
    app.kubernetes.io/name: zesty
rules:
  - apiGroups:
      - ""
    resources:
      - configmaps
      - events
      - namespaces
      - nodes
      - persistentvolumeclaims
      - persistentvolumes
      - pods
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - apps
    resources:
      - deployments
      - replicasets
      - daemonsets
      - statefulsets
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - policy
    resources:
      - poddisruptionbudgets
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - "karpenter.sh"
    resources:
      - nodepools
      - nodeclaims
    verbs:
      - get
      - list
      - watch
