apiVersion: v1
kind: ConfigMap
metadata:
  name: zesty
  namespace: {{ .Values.namespace }}
  annotations:
    meta.helm.sh/release-name: zesty
    meta.helm.sh/release-namespace: {{ .Values.namespace }} 
  labels:
    app.kubernetes.io/instance: zesty
    app.kubernetes.io/name: zesty
data:
  org-id: {{ .Values.orgID }}
