{{- if .Values.awsCluster }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: "aws-cluster-secret"
spec:
  secretStoreRef:
    name: aws-secret-manager-secretstore
    kind: ClusterSecretStore
  target:
    name: "aws-cluster-secret"
  dataFrom:
  - extract:
    key: zesty/access-credentials
    conversionStrategy: Default
    decodingStrategy: None
    metadataPolicy: None
{{- end }}
