apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: zesty-default
  labels:
    app.kubernetes.io/instance: zesty
    app.kubernetes.io/name: zesty
rules:
  - apiGroups:
      - ""
    resources:
      - nodes
      - namespaces
      - persistentvolumes
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - "karpenter.sh"
    resources:
      - nodepools
      - nodeclaims
    verbs:
      - get
      - list
      - watch