apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ include "zesty-k8s.fullname" . }}"
  labels:
    app.kubernetes.io/instance: "{{ include "zesty-k8s.fullname" . }}"
    app.kubernetes.io/name: "{{ include "zesty-k8s.fullname" . }}"
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: "{{ include "zesty-k8s.fullname" . }}"
      app.kubernetes.io/name: "{{ include "zesty-k8s.fullname" . }}"
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: "{{ include "zesty-k8s.fullname" . }}"
        app.kubernetes.io/name: "{{ include "zesty-k8s.fullname" . }}"
    spec:
      automountServiceAccountToken: true
      containers:
        - image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          name: "{{ include "zesty-k8s.name" . }}"
          {{- with .Values.resources }}
          resources:
          {{- toYaml . | nindent 12 }}
          {{- end }}
          securityContext:
          {{- toYaml .Values.container.securityContext | nindent 12 }}
          volumeMounts:
            - mountPath: {{ .Values.persistence.mountPath }}
              name: {{ .Values.persistence.volumeName }}
          env:
            - name: org_id
              valueFrom:
                configMapKeyRef:
                  name: "{{ include "zesty-k8s.configmap" . }}"
                  key: orgID
          {{- if ne .Values.encryptedCredentials ""}}
            - name: encrypted_credentials
              value: {{ .Values.encryptedCredentials | quote }}
          {{- end }}
          {{- if eq .Values.encryptedCredentials "" }}
          envFrom:
          - secretRef:
                name: {{ .Values.secret.name | quote }}
           {{- end }}
      priorityClassName: system-cluster-critical
      securityContext:
      {{- toYaml .Values.securityContext | nindent 8 }}
      serviceAccountName: "{{ include "zesty-k8s.saname" . }}"
      shareProcessNamespace: true
      volumes:
        - name: {{ .Values.persistence.volumeName }}
          persistentVolumeClaim:
            claimName: "{{ include "zesty-k8s.pvcname" . }}"
