apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.pvc.claim }}
  namespace: {{ .Values.namespace }} 
  annotations:
    meta.helm.sh/release-name: zesty
    meta.helm.sh/release-namespace: {{ .Values.namespace }} 
  labels:
    app.kubernetes.io/instance: zesty
    app.kubernetes.io/name: zesty
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
