apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.pvc.claim }}
  labels:
    app.kubernetes.io/instance: zesty
    app.kubernetes.io/name: zesty
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
