{{- if eq .Values.createClusterRole false }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: zesty
  labels:
    app.kubernetes.io/instance: zesty
    app.kubernetes.io/name: zesty
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: zesty
subjects:
  - kind: ServiceAccount
    name: zesty
{{- end -}}
