apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccount.name }}
  namespace: {{ .Values.namespace }} 
  annotations:
    meta.helm.sh/release-name: zesty
    meta.helm.sh/release-namespace: {{ .Values.namespace }} 
  labels:
    app.kubernetes.io/instance: zesty
    app.kubernetes.io/name: zesty
