apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccount.name }}
  namespace: zesty
  annotations:
    meta.helm.sh/release-name: zesty
    meta.helm.sh/release-namespace: zesty
  labels:
    app.kubernetes.io/instance: zesty
    app.kubernetes.io/name: zesty
