orgID: ""
# if you put the value here, the secret won't be used.
encryptedCredentials: ""
secret:
  name: zesty-k8s-agent-creds

image:
  repository: "473301030746.dkr.ecr.us-west-2.amazonaws.com/zesty-k8s/agent"
  pullPolicy: IfNotPresent
  tag: "latest"

persistence:
  volumeName: "zesty-pv-storage"
  mountPath: "/bin/db"
  claim: "zesty-pvc"
  spec:
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 1Gi

serviceAccount:
  name: "zesty"
  annotations:

container:
  securityContext:
    allowPrivilegeEscalation: false
    capabilities:
      drop:
        - ALL
    readOnlyRootFilesystem: true

securityContext:
  fsGroup: 65532
  runAsGroup: 65532
  runAsNonRoot: true
  runAsUser: 65532
  seccompProfile:
    type: RuntimeDefault

resources:
  limits:
    cpu: 1000m
  requests:
    cpu: 100m
