orgID: ""
encryptedCredentials: ""
namespace: "zesty"

image:
  repository: "473301030746.dkr.ecr.us-west-2.amazonaws.com/zesty-k8s/agent"
  pullPolicy: IfNotPresent
  tag: "latest"

pvc:
  volumeName: "zesty-pv-storage"
  mountPath: "/bin/db"
  claim: "zesty-pvc"

serviceAccount:
  name: "zesty"
