orgID: ""
# if you put the value here, the secret won't be used.
encryptedCredentials: ""
secret:
  name: zesty-k8s-agent-creds
  key: "zesty-k8s/encrypted-creds"

awsCluster:
  # if you put the values here, the secret won't be used.
  accessKeyID: ""
  secretAccessKey: ""
  secret:
    name: aws-cluster-secret
    key: "zesty/access-credentials"

log:
  level: 0
  remote: true

image:
  repository: "672188301118.dkr.ecr.eu-west-1.amazonaws.com/zesty-k8s/agent"
  migrationRepository: "672188301118.dkr.ecr.eu-west-1.amazonaws.com/zesty-k8s/agent/migration"
  pullPolicy: IfNotPresent
  tag: "1.46.4"
nodeSelector: {}

tolerations: []

nameOverride: ~
fullnameOverride: ~
namespaceOverride: ~

persistence:
  volumeName: "zesty-pv-storage"
  mountPath: "/bin/db"
  spec:
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 1Gi

serviceAccount:
  annotations:

container:
  securityContext:
    allowPrivilegeEscalation: false
    capabilities:
      drop:
        - ALL
    readOnlyRootFilesystem: true

securityContext:
  fsGroup: 65532
  runAsGroup: 65532
  runAsNonRoot: true
  runAsUser: 65532
  seccompProfile:
    type: RuntimeDefault

resources:
  limits:
    cpu: 1000m
  requests:
    cpu: 100m

prometheus:
  url: ~
  username: ~
  password: ~
  bearerToken: ~

awsAthena:
  enabled: false
  athenaProjectID: ~
  athenaBucketName: ~
  athenaRegion: ~
  athenaDatabase: ~
  athenaTable: ~
  athenaWorkgroup: ~
  athenaCatalog: ~

s3override:
  enabled: false
  bucket: ~
  region: ~

grpc:
  enabled: false
  client:
    endpoint: ~
    port: 50051
  server:
    port: 50052

health:
  port: 9000

config:
  manager:
    enable: false

metricsServer:
  enabled: false # enable it to install metrics-server
